apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: sample
  name: sample
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
