apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample
  name: sample
spec:
  type: ClusterIP
  ports:
  - name: sample
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample