apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-api-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-service-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-service-api
    spec:
      containers:
      - name: sample-service-api
        image: myrepo/myapp
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - name: sample-api-prt
          containerPort: 8080